### PR TITLE
Interoperability between ee.Dictionary and ee.FeatureCollection

### PR DESCRIPTION
**Pull request by fitoprincipe**
Provide a way to convert a `ee.Dictionary` into a `ee.FeatureCollection` and viceversa.

### CODE REVIEW

**Comment by 12rambau** [comment]
Can you split `toTable` and `ToDictionary` into 2 different PR so we can review them separately? I think the `toDictionary` is almost ready to go but I would like to spend more time on the `toTable` one.

**Review by 12rambau — CHANGES_REQUESTED** [review]
Can you split `toTable` and `ToDictionary` into 2 different PR so we can review them separately? I think the `toDictionary` is almost ready to go but I would like to spend more time on the `toTable` one.

**Comment by fitoprincipe** [comment]
should we close this one?

**Comment by 12rambau** [comment]
superseded by https://github.com/gee-community/geetools/pull/372 and https://github.com/gee-community/geetools/pull/373

**Pull request closed without merging**
